// packages/cli/frameworks/solid/template/src/components/series/create/component.solid.tsx
import { Component } from 'solid-js';
import { createStore } from 'solid-js/store';

import { EditorSerieComponent } from '../editor/component.solid';
import { CreateSerieController } from './controller';

export const CreateSerieComponent: Component = () => {
  const [store, setStore] = createStore<CreateSerieController>(
    new CreateSerieController({
      hooks: {
        doRender: () => setStore({}),
      },
    })
  );

  return (
    <form
      onSubmit={(event: Event) => {
        event.preventDefault();
        event.stopPropagation();
        store.onSubmit();
      }}
    >
      <h2>Create a new measuring serie</h2>
      <EditorSerieComponent editorForm={store.editorForm} />
      <button className="primary" type="submit" id="submit">
        Add
      </button>
      <button
        className="btn"
        type="reset"
        id="cancel"
        onClick={() => {
          store.onCancel();
        }}
      >
        Abbrechen
      </button>
    </form>
  );
};

// cli/frameworks/preact/template/src/components/series/create/component.preact.tsx
import { h } from 'preact';

import { PreactComponent } from '../../component.preact';
import { EditorSerieComponent } from '../editor/component.preact';
import { CreateSerieController } from './controller';

export class CreateSerieComponent extends PreactComponent {
  public constructor(props: any) {
    super(props, new CreateSerieController());
  }

  public render() {
    return (
      <form
        onSubmit={(event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          this.$ctrl.onSubmit();
        }}
      >
        <h5>Create a new measuring serie</h5>
        <EditorSerieComponent editorForm={this.$ctrl.editorForm} />
        <button className="btn btn-primary" type="submit" id="submit">
          Add
        </button>
        <button
          className="btn"
          type="reset"
          id="cancel"
          onClick={() => {
            this.$ctrl.onCancel();
          }}
        >
          Abbrechen
        </button>
      </form>
    );
  }
}
