// packages/cli/frameworks/solid/template/src/components/series/list/component.solid.tsx
import { Component, createSignal } from 'solid-js';

import { MeasuredSerieModel } from '../../../models/measured-series.model';
import { ListSerieController } from './controller';

export const ListSerieComponent: Component = () => {
  const [store, setStore] = createSignal<ListSerieController>({} as ListSerieController);
  const ctrl = new ListSerieController({
    hooks: {
      doRender: () => {
        setStore({ ...ctrl } as ListSerieController);
      },
    },
  });
  setStore(ctrl);
  return (
    <div>
      <h2>List</h2>
      <div>
        <button
          className="primary"
          id="add"
          type="button"
          onClick={() => {
            ctrl.add();
          }}
        >
          Add
        </button>
        {store().showPerformanceButton && (
          <button
            className="secondary"
            id="start"
            type="button"
            onClick={() => {
              ctrl.onStart();
            }}
          >
            Performance
          </button>
        )}
      </div>
      {store().elements.map(() => {
        return (
          <table className="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                <th scope="col">Unit</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {store().measuredSeries.map((serie: MeasuredSerieModel, index: number) => {
                return (
                  <tr>
                    <td>{index + 1}</td>
                    <td>{serie.getId()}</td>
                    <td>{serie.getTitle()}</td>
                    <td>{serie.getUnit()}</td>
                    <td>
                      <button
                        id={`edit-${index}`}
                        type="button"
                        onClick={() => {
                          ctrl.edit(serie);
                          setStore({ ...ctrl } as ListSerieController);
                        }}
                      >
                        Edit
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        );
      })}
      <small>Duration: {store().duration} ms</small>
    </div>
  );
};

// packages/create-leanup/templates/angular/src/components/series/list/component.angular.ts
import { ApplicationRef, Component, Inject } from '@angular/core';
import { GenericComponent } from '@leanup/lib';

import { ListSerieController } from './controller';

@Component({
  selector: 'list-serie',
  template: `
    <div>
      <h2>List</h2>
      <div>
        <button class="primary" id="add" type="button" (click)="ctrl.add()">Add</button>
        <button class="secondary" id="start" type="button" *ngIf="ctrl.showPerformanceButton" (click)="ctrl.onStart()">
          Performance
        </button>
      </div>
      <table *ngFor="let element of ctrl.elements; index as i">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Unit</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let serie of ctrl.measuredSeries; index as i">
            <td>{{ i + 1 }}</td>
            <td>{{ serie.getId() }}</td>
            <td>{{ serie.getTitle() }}</td>
            <td>{{ serie.getUnit() }}</td>
            <td>
              <button id="edit-{{ i }}" type="button" (click)="ctrl.edit(serie)">Edit</button>
            </td>
          </tr>
        </tbody>
      </table>
      <small>Duration: {{ ctrl.duration }} ms</small>
    </div>
  `,
})
export class ListSerieComponent implements GenericComponent {
  public readonly ctrl: ListSerieController;

  public constructor(@Inject(ApplicationRef) appRef: ApplicationRef) {
    this.ctrl = new ListSerieController({
      hooks: {
        doRender: appRef.tick.bind(this),
      },
    });
  }
}
