// packages/cli/create-leanup/templates/solid/src/components/series/editor/component.solid.tsx
import { Component } from 'solid-js';

import { InputControl } from '@leanup/form';

import { InputComponent } from '../../input/component.solid';
import { EditorForm } from './editor.form';

interface Props {
  editorForm: EditorForm;
}

export const EditorSerieComponent: Component<Props> = (props: Props) => {
  return (
    <div>
      <InputComponent control={props.editorForm.getControl('title') as InputControl} />
      <InputComponent control={props.editorForm.getControl('unit') as InputControl} />
    </div>
  );
};

// packages/cli/frameworks/preact/template/src/components/series/editor/component.preact.tsx
import { Component, h, JSX } from 'preact';

import { InputControl } from '@leanup/form';
import { GenericComponent } from '@leanup/lib';

import { InputComponent } from '../../input/component.preact';
import { EditorSerieController } from './controller';
import { EditorForm } from './editor.form';

interface Props {
  editorForm: EditorForm;
}

export class EditorSerieComponent extends Component<Props, unknown> implements GenericComponent {
  public ctrl: EditorSerieController = new EditorSerieController();

  public render(): JSX.Element {
    return (
      <div>
        <InputComponent control={this.props.editorForm.getControl('title') as InputControl} />
        <InputComponent control={this.props.editorForm.getControl('unit') as InputControl} />
      </div>
    );
  }
}
