// cli/frameworks/react/template/src/components/series/edit/component.react.tsx
import React from 'react';

import { ReactComponent } from '../../component.react';
import { EditorSerieComponent } from '../editor/component.react';
import { EditSerieController } from './controller';

export class EditSerieComponent extends ReactComponent {
  public constructor(props: any) {
    super(props, new EditSerieController(props.resolvedRoute.params.id));
    this.handleDelete.bind(this);
  }

  private handleDelete() {
    this.$ctrl.onDelete();
  }

  public render() {
    return (
      <form
        onSubmit={(event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          this.$ctrl.onSubmit();
        }}
      >
        <h5>Edit a existing measuring serie</h5>
        <EditorSerieComponent editorForm={this.$ctrl.editorForm} />
        <button className="btn btn-primary" type="submit" id="submit">
          Edit
        </button>
        <button
          className="btn btn-secondary"
          type="reset"
          id="cancel"
          onClick={() => {
            this.$ctrl.onCancel();
          }}
        >
          Abbrechen
        </button>
        <button
          className="btn btn-danger"
          id="delete"
          type="button"
          onClick={() => {
            this.handleDelete();
          }}
        >
          Delete
        </button>
      </form>
    );
  }
}

// packages/create-leanup/templates/solid/src/components/series/edit/component.solid.tsx
import { Component, createSignal } from 'solid-js';

import { ResolvedRoute } from '../../app/controller';
import { EditorSerieComponent } from '../editor/component.solid';
import { EditSerieController } from './controller';

interface Props {
  resolvedRoute: ResolvedRoute;
}

export const EditSerieComponent: Component<Props> = (props: Props) => {
  const [_store, setStore] = createSignal<EditSerieController>({} as EditSerieController, { equals: false });
  const ctrl = new EditSerieController({
    hooks: {
      doRender: () => {
        setStore({ ...ctrl } as EditSerieController);
      },
    },
  });
  setStore(ctrl);

  ctrl.changeMeasuredSerie(parseInt(props.resolvedRoute.data?.id || '0'));

  return (
    <form
      onSubmit={(event: Event) => {
        event.preventDefault();
        event.stopPropagation();
        ctrl.onSubmit();
      }}
    >
      <h2>Edit a existing measuring serie</h2>
      <EditorSerieComponent editorForm={ctrl.editorForm} />
      <button className="primary" type="submit" id="submit">
        Edit
      </button>
      <button
        className="secondary"
        type="reset"
        id="cancel"
        onClick={() => {
          ctrl.onCancel();
        }}
      >
        Abbrechen
      </button>
      <button
        className="danger"
        id="delete"
        type="button"
        onClick={() => {
          ctrl.onDelete();
        }}
      >
        Delete
      </button>
    </form>
  );
};
