// packages/cli/frameworks/angular/template/src/components/input/component.angular.ts
import { Component, Input } from '@angular/core';
import { InputControl } from '@leanup/form/controls/controls';

@Component({
  selector: 'app-input',
  template: `
    <div>
      <label for="{{ control.id }}">{{ control.label }}</label>
      <input id="{{ control.id }}" name="{{ control.name }}" [value]="control.value" />
    </div>
  `,
})
export class InputComponent {
  @Input() public control: InputControl;

  public onChange(event: Event) {
    this.control.value = event.target === null ? '' : event.target.value;
  }
}

// packages/cli/create-leanup/templates/solid/src/components/input/component.solid.tsx
import { Component } from 'solid-js';

import { InputControl } from '@leanup/form';

interface Props {
  control: InputControl;
}

export const InputComponent: Component<Props> = (props: Props) => {
  return (
    <div className="form-group">
      <label htmlFor={props.control.id}>{props.control.label}</label>
      <input
        className="form-control"
        id={props.control.id}
        name={props.control.name}
        value={props.control.value as string}
        onChange={(event) => {
          props.control.value = event.target === null ? '' : event.target.value;
        }}
      />
    </div>
  );
};
