// packages/cli/frameworks/angular/template/src/components/series/edit/component.angular.ts
import { Component, Input, OnChanges } from '@angular/core';
import { GenericComponent } from '@leanup/lib/components/generic';

import { ResolvedRoute } from '../../app/controller';
import { EditSerieController } from './controller';

@Component({
  selector: 'edit-serie',
  template: `
    <form (ngSubmit)="ctrl.onSubmit()">
      <h2>Edit a existing measuring serie</h2>
      <editor-serie [editorForm]="ctrl.editorForm"></editor-serie>
      <button class="primary" type="submit" id="submit">Edit</button>
      <button class="secondary" type="reset" id="cancel" (click)="ctrl.onCancel()">Abbrechen</button>
      <button class="danger" id="delete" type="button" (click)="ctrl.onDelete()">Delete</button>
    </form>
  `,
})
export class EditSerieComponent implements OnChanges, GenericComponent {
  public ctrl: EditSerieController = new EditSerieController();
  @Input() public resolvedRoute: ResolvedRoute;

  public ngOnChanges(): void {
    this.ctrl.changeMeasuredSerie(parseInt(this.resolvedRoute.data?.id || '0'));
  }
}

// packages/cli/frameworks/preact/template/src/components/series/edit/component.preact.tsx
import { JSX } from 'preact';

import { GenericComponent } from '@leanup/lib/components/generic';
import { PreactComponent } from '@leanup/lib/components/preact';

import { ResolvedRoute } from '../../app/controller';
import { EditorSerieComponent } from '../editor/component.preact';
import { EditSerieController } from './controller';

interface Props {
  resolvedRoute: ResolvedRoute;
}

export class EditSerieComponent extends PreactComponent<Props, EditSerieController> implements GenericComponent {
  public ctrl: EditSerieController = new EditSerieController();

  public constructor(props: Props) {
    super(props);
    this.ctrl.changeMeasuredSerie(parseInt(props.resolvedRoute.data?.id || '0'));
  }

  public render(): JSX.Element {
    return (
      <form
        onSubmit={(event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          this.ctrl.onSubmit();
        }}
      >
        <h2>Edit a existing measuring serie</h2>
        <EditorSerieComponent editorForm={this.ctrl.editorForm} />
        <button className="primary" type="submit" id="submit">
          Edit
        </button>
        <button
          className="secondary"
          type="reset"
          id="cancel"
          onClick={() => {
            this.ctrl.onCancel();
          }}
        >
          Abbrechen
        </button>
        <button
          className="danger"
          id="delete"
          type="button"
          onClick={() => {
            this.ctrl.onDelete();
          }}
        >
          Delete
        </button>
      </form>
    );
  }
}
