// packages/cli/frameworks/preact/template/src/components/series/create/component.preact.tsx
import { Component, h, JSX } from 'preact';

import { GenericComponent } from '@leanup/lib';

import { EditorSerieComponent } from '../editor/component.preact';
import { CreateSerieController } from './controller';

export class CreateSerieComponent extends Component<unknown, unknown> implements GenericComponent {
  public readonly ctrl: CreateSerieController;

  public constructor(props: unknown) {
    super(props);
    this.ctrl = new CreateSerieController({
      hooks: {
        doRender: this.forceUpdate.bind(this),
      },
    });
  }

  public render(): JSX.Element {
    return (
      <form
        onSubmit={(event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          this.ctrl.onSubmit();
        }}
      >
        <h2>Create a new measuring serie</h2>
        <EditorSerieComponent editorForm={this.ctrl.editorForm} />
        <button className="primary" type="submit" id="submit">
          Add
        </button>
        <button
          className="secondary"
          type="reset"
          id="cancel"
          onClick={() => {
            this.ctrl.onCancel();
          }}
        >
          Abbrechen
        </button>
      </form>
    );
  }
}

// packages/cli/frameworks/angular/template/src/components/series/create/component.angular.ts
import { ApplicationRef, Component, Inject } from '@angular/core';
import { GenericComponent } from '@leanup/lib';

import { CreateSerieController } from './controller';

@Component({
  selector: 'create-serie',
  template: `
    <form (ngSubmit)="ctrl.onSubmit()">
      <h2>Create a new measuring serie</h2>
      <editor-serie [editorForm]="ctrl.editorForm"></editor-serie>
      <button class="primary" type="submit" id="submit">Add</button>
      <button class="secondary" type="reset" id="cancel" (click)="ctrl.onCancel()">Abbrechen</button>
    </form>
  `,
})
export class CreateSerieComponent implements GenericComponent {
  public readonly ctrl: CreateSerieController;

  public constructor(@Inject(ApplicationRef) appRef: ApplicationRef) {
    this.ctrl = new CreateSerieController({
      hooks: {
        doRender: appRef.tick.bind(this),
      },
    });
  }
}
