// cli/frameworks/react/template/src/components/series/edit/component.react.tsx
import React from 'react';

import { ReactComponent } from '../../component.react';
import { EditorSerieComponent } from '../editor/component.react';
import { EditSerieController } from './controller';

export class EditSerieComponent extends ReactComponent {
  public constructor(props: any) {
    super(props, new EditSerieController(props.resolvedRoute.params.id));
    this.handleDelete.bind(this);
  }

  private handleDelete() {
    this.$ctrl.onDelete();
  }

  public render() {
    return (
      <form
        onSubmit={(event: Event) => {
          event.preventDefault();
          event.stopPropagation();
          this.$ctrl.onSubmit();
        }}
      >
        <h5>Edit a existing measuring serie</h5>
        <EditorSerieComponent editorForm={this.$ctrl.editorForm} />
        <button className="btn btn-primary" type="submit" id="submit">
          Edit
        </button>
        <button
          className="btn btn-secondary"
          type="reset"
          id="cancel"
          onClick={() => {
            this.$ctrl.onCancel();
          }}
        >
          Abbrechen
        </button>
        <button
          className="btn btn-danger"
          id="delete"
          type="button"
          onClick={() => {
            this.handleDelete();
          }}
        >
          Delete
        </button>
      </form>
    );
  }
}

// cli/frameworks/angular/template/src/components/series/edit/component.angular.ts
import { Component, Input, OnChanges } from '@angular/core';

import { EditSerieController } from './controller';

@Component({
  selector: 'edit-serie',
  template: `
    <form (ngSubmit)="$ctrl.onSubmit()">
      <h5>Edit a existing measuring serie</h5>
      <editor-serie [editorForm]="$ctrl.editorForm"></editor-serie>
      <button class="btn btn-primary" type="submit" id="submit">Edit</button>
      <button class="btn btn-secondary" type="reset" id="cancel" (click)="$ctrl.onCancel()">
        Abbrechen
      </button>
      <button class="btn btn-danger" id="delete" type="button" (click)="$ctrl.onDelete()">
        Delete
      </button>
    </form>
  `,
})
export class EditSerieComponent implements OnChanges {
  public $ctrl: EditSerieController = new EditSerieController(null);
  @Input() public resolvedRoute: any;

  public ngOnChanges() {
    this.$ctrl.changeMeasuredSerie(this.resolvedRoute.params.id);
  }
}
