// packages/cli/create-leanup/templates/solid/src/components/input/component.solid.tsx
import { Component } from 'solid-js';

import { InputControl } from '@leanup/form';

interface Props {
  control: InputControl;
}

export const InputComponent: Component<Props> = (props: Props) => {
  return (
    <div className="form-group">
      <label htmlFor={props.control.id}>{props.control.label}</label>
      <input
        className="form-control"
        id={props.control.id}
        name={props.control.name}
        value={props.control.value as string}
        onChange={(event) => {
          props.control.value = event.target === null ? '' : event.target.value;
        }}
      />
    </div>
  );
};

// packages/doc/src/components/input/component.preact.tsx
import { h } from 'preact';

import { PreactComponent } from '../component.preact';

export class InputComponent extends PreactComponent {
  public render() {
    return (
      <div className="form-group">
        <label htmlFor={this.props.control.id}>{this.props.control.label}</label>
        <input
          className="form-control"
          id={this.props.control.id}
          name={this.props.control.name}
          value={this.props.control.value}
          onChange={(event: Event) => {
            this.props.control.value = event.target.value;
            this.forceUpdate();
          }}
        />
      </div>
    );
  }
}
