// packages/create-leanup/templates/react/src/react.main.tsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import * as PACKAGE_JSON from 'react/package.json';

import { run } from './app.run';
import { AppComponent } from './components/app/component.react';
import { typeIt } from './shares/utils';

const TYPED_PACKAGE_JSON = typeIt<{ version: string }>(PACKAGE_JSON);

run('React', TYPED_PACKAGE_JSON.version, () => {
  const htmlDivElement: HTMLDivElement | null = document.querySelector('div#react');
  if (htmlDivElement instanceof HTMLDivElement) {
    const root = createRoot(htmlDivElement);
    root.render(<AppComponent />);
  }
});

// packages/cli/create-leanup/templates/solid/src/solid.main.tsx
import { render } from 'solid-js/web';

import * as PACKAGE_JSON from '../node_modules/solid-js/package.json';
import { run } from './app.run';
import { AppComponent } from './components/app/component.solid';
import { typeIt } from './shares/utils';

const TYPED_PACKAGE_JSON = typeIt<{ version: string }>(PACKAGE_JSON);

run('Solid', TYPED_PACKAGE_JSON.version, () => {
  const htmlDivElement: HTMLDivElement | null = document.querySelector('div#solid');
  if (htmlDivElement instanceof HTMLDivElement) {
    render(() => <AppComponent />, htmlDivElement);
  }
});
