// packages/cli/frameworks/preact/template/src/preact.main.tsx
import 'preact/debug';

import { h, render } from 'preact';
import * as PACKAGE_JSON from 'preact/package.json';

import { run } from './app.run';
import { AppComponent } from './components/app/component.preact';
import { typeIt } from './shares/utils';

const TYPED_PACKAGE_JSON = typeIt<{ version: string }>(PACKAGE_JSON);

run('Preact', TYPED_PACKAGE_JSON.version, () => {
  const htmlDivElement: HTMLDivElement | null = document.querySelector('div#preact');
  if (htmlDivElement instanceof HTMLDivElement) {
    render(<AppComponent />, htmlDivElement);
  }
});

// packages/cli/create-leanup/templates/solid/src/solid.main.tsx
import { render } from 'solid-js/web';

import * as PACKAGE_JSON from '../node_modules/solid-js/package.json';
import { run } from './app.run';
import { AppComponent } from './components/app/component.solid';
import { typeIt } from './shares/utils';

const TYPED_PACKAGE_JSON = typeIt<{ version: string }>(PACKAGE_JSON);

run('Solid', TYPED_PACKAGE_JSON.version, () => {
  const htmlDivElement: HTMLDivElement | null = document.querySelector('div#solid');
  if (htmlDivElement instanceof HTMLDivElement) {
    render(() => <AppComponent />, htmlDivElement);
  }
});
