// packages/cli/frameworks/preact/template/src/components/series/editor/component.preact.tsx
import { h, JSX } from 'preact';

import { InputControl } from '@leanup/form/controls/controls';
import { GenericComponent } from '@leanup/lib/components/generic';
import { PreactComponent } from '@leanup/lib/components/preact';

import { InputComponent } from '../../input/component.preact';
import { EditorSerieController } from './controller';
import { EditorForm } from './editor.form';

interface Props {
  editorForm: EditorForm;
}

export class EditorSerieComponent extends PreactComponent<Props, unknown> implements GenericComponent { {
  public ctrl: EditorSerieController = new EditorSerieController();

  public render(): JSX.Element {
    return (
      <div>
        <InputComponent control={this.props.editorForm.getControl('title') as InputControl} />
        <InputComponent control={this.props.editorForm.getControl('unit') as InputControl} />
      </div>
    );
  }
}

// packages/cli/frameworks/angular/template/src/components/series/editor/component.angular.ts
import { Component, Input, OnChanges } from '@angular/core';
import { InputControl } from '@leanup/form/controls/controls';
import { GenericComponent } from '@leanup/lib/components/generic';

import { EditorSerieController } from './controller';
import { EditorForm } from './editor.form';

@Component({
  selector: 'editor-serie',
  template: `
    <div>
      <app-input [control]="titleInput"></app-input>
      <app-input [control]="unitInput"></app-input>
    </div>
  `,
})
export class EditorSerieComponent implements GenericComponent, OnChanges {
  public readonly ctrl: EditorSerieController = new EditorSerieController();

  @Input() public editorForm!: EditorForm;
  public titleInput: InputControl = new InputControl('title');
  public unitInput: InputControl = new InputControl('title');

  public ngOnChanges(): void {
    this.titleInput = <InputControl>this.editorForm.getControl('title');
    this.unitInput = <InputControl>this.editorForm.getControl('unit');
  }
}
